const API_BASE='https://dhanu-movies-api.dhanushrdhanushr518.workers.dev';
const fallback=[
{id:'demo1',title:'Beyond the Silence',year:2026,genres:['Drama'],runtime:'2h 04m',rating:'8.6',type:'movie',image:'https://images.unsplash.com/photo-1485846234645-a62644f84728?w=900&auto=format&fit=crop&q=80',description:'A cinematic placeholder used until your Telegram catalog is connected.',fileId:null},
{id:'demo2',title:'Neon Skies',year:2026,genres:['Sci-Fi','Action'],runtime:'2h 18m',rating:'8.9',type:'movie',image:'https://images.unsplash.com/photo-1519608487953-e999c86e7455?w=900&auto=format&fit=crop&q=80',description:'A futuristic demo title for the new Dhanu Movies interface.',fileId:null},
{id:'demo3',title:'Echoes of the Mind',year:2025,genres:['Thriller'],runtime:'1h 52m',rating:'8.1',type:'movie',image:'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=900&auto=format&fit=crop&q=80',description:'Demo catalog content. Real records will arrive from your authorized Telegram channel.',fileId:null},
{id:'demo4',title:'Cosmic Drift',year:2025,genres:['Sci-Fi'],runtime:'8 Episodes',rating:'8.4',type:'series',image:'https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?w=900&auto=format&fit=crop&q=80',description:'Demo series card.',fileId:null}
];
let catalog=[...fallback],selected=null,filtered=catalog;
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const imageFor=m=>m.image||(m.thumbFileId&&API_BASE?`${API_BASE}/media/${encodeURIComponent(m.thumbFileId)}`:'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=900&auto=format&fit=crop&q=80');
function card(m){const saved=(JSON.parse(localStorage.getItem('dhanu_list')||'[]')).includes(m.id);const el=document.createElement('article');el.className='movie-card';el.innerHTML=`<div class="poster" style="background-image:url('${imageFor(m)}')"><button class="save" data-save="${esc(m.id)}">${saved?'♥':'♡'}</button></div><div class="card-info"><h3>${esc(m.title)}</h3><small>${esc(m.year)} · ${esc(m.runtime||'')} · ★ ${esc(m.rating||'')}</small></div>`;el.addEventListener('click',e=>{if(e.target.closest('[data-save]')){toggleSave(m.id);return}openDetails(m)});return el}
function renderRow(id,items){const box=$(id);box.innerHTML='';items.slice(0,12).forEach(m=>box.appendChild(card(m)))}
function renderGrid(id,items){const box=$(id);box.innerHTML='';if(!items.length){box.innerHTML='<p style="color:var(--muted)">Nothing here yet.</p>';return}items.forEach(m=>box.appendChild(card(m)))}
function genres(){return ['All',...new Set(catalog.flatMap(m=>m.genres||[]))]}
function renderChips(){const box=$('genreChips');box.innerHTML='';genres().forEach((g,i)=>{const b=document.createElement('button');b.className='chip'+(i===0?' active':'');b.textContent=g;b.onclick=()=>{document.querySelectorAll('.chip').forEach(x=>x.classList.remove('active'));b.classList.add('active');filtered=g==='All'?catalog:catalog.filter(m=>(m.genres||[]).includes(g));renderGrid('movieGrid',filtered.filter(m=>m.type!=='series'&&m.type!=='tv'));};box.appendChild(b)})}
function render(){const movies=catalog.filter(m=>m.type!=='series'&&m.type!=='tv'),series=catalog.filter(m=>m.type==='series'||m.type==='tv');renderRow('trendingRow',catalog);renderRow('continueRow',catalog.slice(0,6));renderGrid('movieGrid',movies);renderGrid('seriesGrid',series);const ids=JSON.parse(localStorage.getItem('dhanu_list')||'[]');renderGrid('libraryGrid',catalog.filter(m=>ids.includes(m.id)));renderChips();const hero=catalog[0];if(hero){$('heroBackdrop').style.backgroundImage=`url('${imageFor(hero)}')`;$('heroTitle').innerHTML=esc(hero.title);$('heroDescription').textContent=hero.description||'Your cinema. Your world.';$('heroMeta').innerHTML=`<span>${esc(hero.year)}</span><span>★ ${esc(hero.rating||'')}</span><span>${esc(hero.runtime||'')}</span>`;$('heroPlay').onclick=()=>play(hero);$('heroInfo').onclick=()=>openDetails(hero)}}
function toggleSave(id){let a=JSON.parse(localStorage.getItem('dhanu_list')||'[]');a=a.includes(id)?a.filter(x=>x!==id):[...a,id];localStorage.setItem('dhanu_list',JSON.stringify(a));render()}
function openDetails(m){selected=m;$('detailCover').style.backgroundImage=`url('${imageFor(m)}')`;$('detailTitle').textContent=m.title;$('detailType').textContent=(m.type==='series'||m.type==='tv')?'SERIES':'MOVIE';$('detailMeta').innerHTML=`<span>${esc(m.year)}</span><span>★ ${esc(m.rating||'')}</span><span>${esc(m.runtime||'')}</span>`;$('detailGenres').innerHTML=(m.genres||[]).map(g=>`<span class="chip">${esc(g)}</span>`).join('');$('detailDescription').textContent=m.description||'No description available.';const ids=JSON.parse(localStorage.getItem('dhanu_list')||'[]');$('detailSave').textContent=ids.includes(m.id)?'♥ Remove from list':'♡ Add to list';$('detailsModal').classList.remove('hidden')}
function play(m){if(!m.fileId){alert('This demo item has no video attached yet. Add a file to the authorized Telegram channel and the catalog will receive it.');return}const url=`${API_BASE}/media/${encodeURIComponent(m.fileId)}`;$('videoPlayer').src=url;$('playerTitle').textContent=m.title;$('playerModal').classList.remove('hidden');$('videoPlayer').play().catch(()=>{})}
async function loadCatalog(){try{const r=await fetch(`${API_BASE}/api/movies`,{cache:'no-store'});if(!r.ok)throw new Error('API '+r.status);const data=await r.json();if(Array.isArray(data)&&data.length)catalog=data;render()}catch(e){console.warn('Dhanu API not connected; using demo catalog.',e);render()}}
$('searchToggle').onclick=()=>$('searchPanel').classList.toggle('open');$('themeToggle').onclick=()=>document.body.classList.toggle('light');$('menuToggle').onclick=()=>document.querySelector('.desktop-nav').classList.toggle('mobile-show');$('searchInput').oninput=e=>{const q=e.target.value.trim().toLowerCase();filtered=catalog.filter(m=>`${m.title} ${(m.genres||[]).join(' ')} ${m.description||''}`.toLowerCase().includes(q));$('searchStatus').textContent=`${filtered.length} result${filtered.length===1?'':'s'}`;renderGrid('movieGrid',q?filtered.filter(m=>m.type!=='series'&&m.type!=='tv'):catalog.filter(m=>m.type!=='series'&&m.type!=='tv'))};$('modalClose').onclick=()=>$('detailsModal').classList.add('hidden');$('playerClose').onclick=()=>{$('videoPlayer').pause();$('videoPlayer').removeAttribute('src');$('playerModal').classList.add('hidden')};$('detailPlay').onclick=()=>selected&&play(selected);$('detailSave').onclick=()=>selected&&toggleSave(selected.id);document.querySelectorAll('.modal').forEach(m=>m.addEventListener('click',e=>{if(e.target===m)m.classList.add('hidden')}));document.addEventListener('DOMContentLoaded',()=>{render();loadCatalog()});